src/routes/utils/returnJSONResponse.js
src/services/events/getEventsPerScope.js
src/services/utils/flatten.js

Either you "set the header" and "send" or you "write the header" and "end" if you know what I mean.

Make JSON work again.

---

src/infrastructure/authorization.js
src/parsers/event/eventsToIcs.js
src/routes/calendar.js

Add calendar names again, in the whole refactoring confusion I removed it... 🙈

Calendar names

---

example_data.sql
schema.sql
wiki/schulcloud-api-requirements.md

This removes hardcoded type UUID and replaces it with string. The central service is going to take care of the uniqueness.

Change type UUID to String

---

src/config.js
src/http/_getRequest.js

wait for https://github.com/schul-cloud/schulcloud-server/pull/227

add x-api-key for resolver services

---

README.md
package.json
src/config.js

more detailed and updated readme and prepared config.js for easy switch to local development

update readme and config.js

---

Dockerfile
src/infrastructure/database.js

Change the Object what is given to pg.connet from an URI String to an Object with attributes.
The Object that is know given to pg.connect has a better handling for long passwords.
https://ticketsystem.schul-cloud.org/browse/SC-5849
The Object waht is geiven to pg connect.
Better handling of long passwords

feature/SC-5849 - PostgreSQL Connection Parameter change from URI to an Object

---

.github/workflows/build-and-push-docker-image.yaml
Makefile

Feature/ops 1474/push develop latest

---

Makefile

add force push for develop to override existing dockertag

---

CHANGELOG.md
Makefile

- x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

test without force

---

.github/workflows/main.yml

Correctly reading full branch name

---

CHANGELOG.md
package-lock.json
package.json
src/config.js

- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8512
- Setting IS_MIGRATION flag

SC-8512 events duplicates

---

CHANGELOG.md
package-lock.json
package.json
src/routes/events.js

SC-8604 - fix deletion route

---

CHANGELOG.md
ansible/roles/schulcloud-calendar/templates/deployment.yml.j2

Reduce resource consumption for deployed client.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-92
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 128mb and 1gb.
Set the default pod count to 1 pod

BC-37 - BC-92 - reduce resource consumption for deployed schulcloud-calendar

---

CHANGELOG.md
ansible/roles/schulcloud-calendar/templates/configmap.yml.j2
package-lock.json
package.json
src/config.js

This PR is about updating the server callback route. 
https://ticketsystem.hpi-schul-cloud.org/browse/BC-83

SC-9192 BC-69 BC-83 add versioned basepath

---

CHANGELOG.md

Add ansible files for Bosscloud (default)
https://ticketsystem.hpi-schul-cloud.org/browse/BC-38
https://ticketsystem.hpi-schul-cloud.org/browse/BC-127
hpi-schul-cloud/schulcloud-server#2939
hpi-schul-cloud/schulcloud-client#2664
hpi-schul-cloud/nuxt-client#1882
hpi-schul-cloud/superhero-dashboard#127
hpi-schul-cloud/schulcloud-editor#75
hpi-schul-cloud/dof_app_deploy#29
Add ansible files for Bosscloud (default)

BC-38 - BC-127 - Add ansible files for Bosscloud (default)

---

ansible/roles/schulcloud-calendar/tasks/main.yml

The configmap with an file in it must create before it were used at the job template. 
The last part should be the Deployment self. 

Fix Deploymend order

---

ansible/roles/schulcloud-calendar/templates/configmap_file_init_db.yml.j2

bc-111 wait for postgres to spin up

---

.github/workflows/clean.yml
CHANGELOG.md

Fix for mistake on branch delete event.
It's not GITHUB_REF what shoud be usedm but github.event.ref.
The actions are triggered on the main branch, so GITHUB_REF shows to main and github.event.ref has the branchname of the deleted branch.
https://docs.github.com/en/rest/reference/git#delete-a-reference
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3190
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1959
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2716
- https://github.com/hpi-schul-cloud/antivirus_check_service/pull/14
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/138
More and detailed information on the _definition of done_ can be found …

BC-589 fix clean job

---

ansible/roles/schulcloud-calendar-core/meta/main.yml
ansible/roles/schulcloud-calendar-init/meta/main.yml

hpi-schul-cloud/antivirus_check_service#19
hpi-schul-cloud/dof_app_deploy#84
hpi-schul-cloud/nuxt-client#2017
hpi-schul-cloud/schulcloud-client#2743
hpi-schul-cloud/schulcloud-server#3270
hpi-schul-cloud/superhero-dashboard#153
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1006

BC-1006 - Meta file for the roles

---

ansible/roles/schulcloud-calendar-init/tasks/main.yml

hpi-schul-cloud/schulcloud-server#3384
hpi-schul-cloud/dof_app_deploy#197

27.10.1 - fixes at ansible roles to main

---

package-lock.json
package.json

hpi-schul-cloud/schulcloud-server#3401
hpi-schul-cloud/schulcloud-client#2817
hpi-schul-cloud/nuxt-client#2122
hpi-schul-cloud/end-to-end-tests#406
hpi-schul-cloud/dof_app_deploy#219

version 27.12.0

---

.github/workflows/push.yml
.github/workflows/tag.yml

BC-2889 limit workflow permissions

---

src/http/getAllScopesForToken.js
src/routes/calendar.js
src/routes/events.js
src/routes/subscriptions.js
src/security/authentication.js
src/security/authorization.js
test/routes/events.integration.test.js

https://ticketsystem.dbildungscloud.de/browse/BC-3170
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3108
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3893

Fix admin calendar

---

package-lock.json
package.json

Update node version to 18. Update libraries that they wouldn't cause high/critical vulnerabilities.
https://ticketsystem.dbildungscloud.de/browse/BC-3071

BC-3071 Update packages versions

---

.github/workflows/push.yml
.github/workflows/tag.yml
Dockerfile
README.md
package-lock.json
package.json

BC-3385 dockerfile with node 18

---

package-lock.json
package.json

https://ticketsystem.dbildungscloud.de/browse/BC-3965

BC-3965 Update npm version

---

.github/workflows/tag.yml

https://ticketsystem.dbildungscloud.de/browse/BC-3778

BC-3778 push container image to quay

---

.github/workflows/tag.yml

BC-3778 fix docker meta service data

---

ansible/group_vars/all/schulcloud-calendar.yml

https://ticketsystem.dbildungscloud.de/browse/BC-4316
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/139
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4207
https://github.com/hpi-schul-cloud/version-aggregator/pull/8
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3217
https://github.com/hpi-schul-cloud/nuxt-client/pull/2599
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/214
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/37

BC-4316 pull images for ref and prod from quay.io

---

.github/workflows/push.yml
ansible/roles/schulcloud-calendar-core/templates/deployment.yml.j2

We need additional Metadata for the git repo, branch/tag, commit hash and the [common-labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) for our kubernetes Deployments and Pods.
BC-5405
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4517
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3343
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/689
https://github.com/hpi-schul-cloud/nuxt-client/pull/2899
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/233
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/43
https://github.com/hpi-schul-cloud/version-aggregator/pull/12
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/5
> Notice: Please remove the WIP label if the PR is ready to review, …

BC-5405 - Metadata on k8s ressources

---

ansible/roles/schulcloud-calendar-core/templates/deployment.yml.j2

To Improve the distribution of PODs to the least number of kubernetes worker nodes who is Required 
but also to secure that the PODs of one Deployment are distributed over the Fault Zones and Node pools
the pod affinity and anti affinity are set.
**Affernety number calculation:** 
**_Assign Number for an host_** = 0 - 20 X _Fault Zone_  - 10 X _Node Pool_ + 9 X _Host_ 
**_Host_**  = 1 if on the host runs an POD from the Schulcloud-Verbund on any namespace
**_Host_**  = 0 if on the host runs no POD from the Schulcloud-Verbund on any namespace
**_Node Pool_** = 1 if on a host of this node pool runs an POD from the Deployment
**_Node Pool_** = 0 if on no host of this node pool runs an POD from the Deployment
**_Fault Pool_** = 1 if on a host of this fault zone runs an POD from the Deployment …

BC-5423 - Add POD affinity and anti-affinity

---

.github/workflows/clean.yml
.github/workflows/dependabot-to-jira.yml
.github/workflows/push.yml
.github/workflows/tag.yml

https://ticketsystem.dbildungscloud.de/browse/BC-6074

BC-6074 updated gh-actions

---

.github/workflows/dependabot-to-jira.yml
.github/workflows/push.yml

https://ticketsystem.dbildungscloud.de/browse/BC-6589
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4771
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3414
https://github.com/hpi-schul-cloud/nuxt-client/pull/3112
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/250
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/157
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/52
https://github.com/hpi-schul-cloud/version-aggregator/pull/19
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/798
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/9
https://github.com/hpi-schul-cloud/tldraw-client/pull/58

BC-6589 update gh-actions

---

.github/workflows/dependabot-to-jira.yml

referencing to variables in a string with single quotes does not work
https://ticketsystem.dbildungscloud.de/browse/BC-6695
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4793
https://github.com/hpi-schul-cloud/nuxt-client/pull/3123
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/158
https://github.com/hpi-schul-cloud/tldraw-client/pull/64

BC-6695 fixup dependabot-to-jira workflow

---

src/config.js
src/infrastructure/databasePromise.js

Added option to enable SSL for the database connection.
If not defined it still defaults to `false`.
[OPS-6085](https://ticketsystem.dbildungscloud.de/browse/OPS-6085)

OPS-6085-allow-encrypted-db-connection

---

ansible/roles/schulcloud-calendar-core/templates/deployment.yml.j2

Add annotations to the kubernetes deployments so that they cann automaticly restart by the stakater reloader if configmaps or secrets change 
- hpi-schul-cloud/schulcloud-server#5265
- hpi-schul-cloud/dof_app_deploy#981
- hpi-schul-cloud/schulcloud-client#3527
- hpi-schul-cloud/nuxt-client#3413
- hpi-schul-cloud/superhero-dashboard#267
- hpi-schul-cloud/shd-client#21
- hpi-schul-cloud/antivirus_check_service#64
- hpi-schul-cloud/version-aggregator#23
- hpi-schul-cloud/h5p-staticfiles-server#12
- hpi-schul-cloud/tldraw-server#20
- hpi-schul-cloud/tldraw-client#100
- https://ticketsystem.dbildungscloud.de/browse/BC-5112

BC-5112 - add Annotations to deployment for Restart

---

package-lock.json
package.json

https://ticketsystem.dbildungscloud.de/browse/BC-7994

BC-7994 Use node --watch instead of nodemon

---

README.md

https://ticketsystem.dbildungscloud.de/browse/BC-8923

BC-8923 Update README

---

.github/workflows/push.yml

https://ticketsystem.dbildungscloud.de/browse/BC-9012

BC-9242 add dependabot ready-for-ci logic to push workflow

---

.github/workflows/push.yml

https://ticketsystem.dbildungscloud.de/browse/BC-9242

BC-9242 add missing gh-workflow trigger

---

package-lock.json
package.json

BC-9323 update dependencies

---

.github/workflows/dependency-review.yml

https://ticketsystem.dbildungscloud.de/browse/BC-9800
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5712
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3644
https://github.com/hpi-schul-cloud/nuxt-client/pull/3715
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/308
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/202
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/90
https://github.com/hpi-schul-cloud/tldraw-client/pull/167
https://github.com/hpi-schul-cloud/dependency-review-config/pull/2

BC-9800 added dependency-review-action
